# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fff1e21ea8974c4055c7396ecade49a30c276d98cac2fe59a06234fc1f45f1083a7a3bebdeb427ae1dff4e52f28c8a1b510a79af65e3a421cadc1ad43b85f2bf

test:
  secret_key_base: 4fbaa12eae7c0be84b5f34040a71975fa026d0f1b1d309b5e4d522a4f876e30a76f83c34c3f8d197da14ff4fc32f31fa2cc719b8ff1203ce0147cb7d808d20e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
